### ISSUE TITLE
`alexSetUserState`/`alexGetUserState` with `monadUserState-bytestring` wrapper

### ISSUE THREAD

**Issue by zoeyfyi** [haskell/alex#220]
Is there any reason these are not enabled for the `monadUserState-bytestring` wrapper?

https://github.com/haskell/alex/blob/24ab083ecf6fc82262090374ef46fb4ae7bbf61c/data/AlexWrappers.hs#L261

**Comment by andreasabel** [comment]
I suggest you try to find the author (e.g. via git blame) and then ask the author...

**Comment by emekoi** [comment]
Tracing the change back to 13fd23e1ea064eac611f1834c58d7b825a4013a9 and 24ab083ecf6fc82262090374ef46fb4ae7bbf61c, it seems that this was a mistake.

**Comment by andreasabel** [comment]
> Tracing the change back to [13fd23e](https://github.com/haskell/alex/commit/13fd23e1ea064eac611f1834c58d7b825a4013a9) and [4de7cd8](https://github.com/haskell/alex/commit/4de7cd8b61ff05b5b2bdf5d4ece03ecf8c35f311), it seems that this was a mistake.

@emekoi : Is there a released version of alex that supports `alex{G,S}etUserState` in the `monadUserState-bytestring` wrapper?
According to my experiments,
- alex-3.1.7 (Jan 2016) does not know about that wrapper
- alex-3.2.0 (Oct 2016) knows about the wrapper but does not support `alex{G,S}etUserState` 

So maybe this isn't a regression, but a feature that never worked.

**Comment by emekoi** [comment]
I probably should've checked if this ever worked, but I think your're right that this never worked. In a4f43f8c1532937673682b317470f8e47fe1be38 (just before 13fd23e1ea064eac611f1834c58d7b825a4013a9) `monadUserState-bytestring` also did not support `alex{G,S}etUserState`. I probably just assumed `alex` did at some point because I was following [this](https://serokell.io/blog/lexing-with-alex#regular-expressions) tutorial by Serokell, and they use `alex{G,S}etUserState` with `monadUserState-bytestring`.

Also could you clarify what you meant by "alex-3.1.7 (Jan 2016) does not know about that wrapper"? Looking at Github, `alex{G,S}etUserState` were introduced in #23 which made it into `alex-3.1.1`, and `monadUserState-bytestring` was introduced in `alex-2.3.1` (57d9d6d30ee28be5d1d02bfa6379d605e132a735).

**Comment by andreasabel** [comment]
> Also could you clarify what you meant by "alex-3.1.7 (Jan 2016) does not know about that wrapper"?

Oh, I got a parse error for the test, so I assumed it was because of the `%wrapper` directive.  I should check again...

**Comment by andreasabel** [comment]
I checked 3.1.4; it also does not know about `alex{S,G}etUserState`.  Older versions of alex can't be built on my mac.
